@App_HostAddress = https://localhost:7002

GET {{App_HostAddress}}/api/todoitems

###

POST {{App_HostAddress}}/api/todoitems
Content-Type: application/json

{
  //TodoItemDTO
}

###

@id=0
DELETE {{App_HostAddress}}/api/todoitems/{{id}}

###

GET {{App_HostAddress}}/api/todoitems/{{id}}

###

PUT {{App_HostAddress}}/api/todoitems/{{id}}
Content-Type: application/json

{
  //TodoItemDTO
}

###
